export * from './actors.service';
import { ActorsService } from './actors.service';
export * from './advanced-analytics.service';
import { AdvancedAnalyticsService } from './advanced-analytics.service';
export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './directors.service';
import { DirectorsService } from './directors.service';
export * from './discovery.service';
import { DiscoveryService } from './discovery.service';
export * from './import.service';
import { ImportService } from './import.service';
export * from './movies.service';
import { MoviesService } from './movies.service';
export * from './recommendations.service';
import { RecommendationsService } from './recommendations.service';
export * from './search.service';
import { SearchService } from './search.service';
export const APIS = [ActorsService, AdvancedAnalyticsService, AnalyticsService, AuthService, DirectorsService, DiscoveryService, ImportService, MoviesService, RecommendationsService, SearchService];
