export * from './advanced-analytics.service';
import { AdvancedAnalyticsService } from './advanced-analytics.service';
export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './import.service';
import { ImportService } from './import.service';
export * from './recommendations.service';
import { RecommendationsService } from './recommendations.service';
export const APIS = [AdvancedAnalyticsService, AnalyticsService, AuthService, ImportService, RecommendationsService];
