/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RookieDto } from './rookie-dto';
import { Items } from './items';


export interface BestRookiesDto { 
    newDirectors: Array<RookieDto>;
    newActors: Array<Items>;
}

