/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BingoSquareDto } from './bingo-square-dto';


export interface BingoGridDto { 
    gridSize: number;
    squares: Array<BingoSquareDto>;
    startDate?: string | null;
    endDate?: string | null;
}

