/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BingoRequest { 
    gridSize?: number;
    scope?: number;
    customSourceIds?: Array<string> | null;
    customSourceTitles?: Array<string> | null;
    excludeWatched?: boolean;
    durationDays?: number | null;
    boardId?: string | null;
}

