/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BingoSquareDto { 
    objectiveId: string;
    description: string;
    isCompleted: boolean;
    completionDate: string | null;
    row: number;
    column: number;
    movieId?: string | null;
    movieTitle?: string | null;
    watchedDate?: string | null;
}

