/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BingoBoardDto { 
    boardId: string;
    gridSize: number;
    startDate: string | null;
    endDate: string | null;
    isCompleted: boolean;
    completedSquares: number;
    totalSquares: number;
    createdAt: string;
    completedOnTime?: boolean;
}

