/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WrappedMovieDto } from './wrapped-movie-dto';


export interface BookendsDto { 
    openingScene: WrappedMovieDto | null;
    fadeToBlack: WrappedMovieDto | null;
}

