/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CastingPairDto { 
    actor1Name?: string;
    actor2Name?: string;
    collaborationCount?: number;
    actor1ProfilePath?: string | null;
    actor2ProfilePath?: string | null;
}

