/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieSimpleDto } from './movie-simple-dto';


export interface CustomListDto { 
    id?: string;
    name?: string;
    createdAt?: string;
    movies?: Array<MovieSimpleDto>;
}

