/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DatabaseStatsDto { 
    totalUsers: number;
    totalMovies: number;
    pendingMovies: number;
    completedMovies: number;
    failedMovies: number;
    notFoundMovies: number;
    permanentlyFailedMovies: number;
    totalTvShows: number;
    totalGenres: number;
    totalDirectors: number;
    totalActors: number;
    totalDiaryEntries: number;
}

