/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiceRollRequest { 
    scope: number;
    diceTypes?: Array<number> | null;
    customSourceIds?: Array<string> | null;
    customSourceTitles?: Array<string> | null;
    excludeWatched?: boolean;
    presets?: { [key: string]: number; } | null;
    partnerUsername?: string | null;
}

