/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MovieSimpleDto } from './movie-simple-dto';


export interface DirectorDetailsDto { 
    id: string;
    name: string;
    averageRating: number;
    watchCount: number;
    movies: Array<MovieSimpleDto>;
}

