/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DirectorActorPairDto { 
    directorName?: string;
    actorName?: string;
    collaborationCount?: number;
    directorProfilePath?: string | null;
    actorProfilePath?: string | null;
}

