/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenreStreakDto { 
    genreName: string;
    streakLength: number;
    startDate: string;
    endDate: string;
}

