/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WrappedMovieDto } from './wrapped-movie-dto';


export interface MonthlyExtremeDto { 
    month: number;
    monthName: string;
    bestMovie: WrappedMovieDto | null;
    worstMovie: WrappedMovieDto | null;
}

