/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeeklyWatchesDto } from './weekly-watches-dto';
import { MonthlyWatchesDto } from './monthly-watches-dto';


export interface MonthlyActivityResponseDto { 
    monthlyActivity: Array<MonthlyWatchesDto>;
    weeklyActivity: Array<WeeklyWatchesDto>;
}

