/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MostRewatchedDto { 
    title: string;
    posterPath: string | null;
    releaseYear: number | null;
    rewatchCount: number;
}

