/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MovieSimpleDto { 
    id: string;
    title: string;
    releaseYear: number | null;
    posterPath: string | null;
    isWatched?: boolean;
}

