/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActorSimpleDto } from './actor-simple-dto';
import { DirectorSimpleDto } from './director-simple-dto';
import { MovieDiaryEntryDto } from './movie-diary-entry-dto';
import { GenreSimpleDto } from './genre-simple-dto';


export interface MovieDetailsDto { 
    id: string;
    title: string;
    releaseYear: number | null;
    runtimeMinutes: number | null;
    posterUrl: string | null;
    overview: string | null;
    tmdbRating: number | null;
    userAverageScore: number | null;
    genres: Array<GenreSimpleDto>;
    directors: Array<DirectorSimpleDto>;
    actors: Array<ActorSimpleDto>;
    diaryEntries: Array<MovieDiaryEntryDto>;
    isWatched: boolean;
}

