/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MysteryBoxHintDto } from './mystery-box-hint-dto';


export interface MysteryBoxDto { 
    boxIds: Array<string>;
    variant: number;
    generatedAt: string;
    hints?: Array<MysteryBoxHintDto> | null;
    filterType?: string | null;
    filterValue?: string | null;
}

