/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MysteryBoxRequest { 
    scope: number;
    variant: number;
    boxCount?: number;
    customSourceIds?: Array<string> | null;
    customSourceTitles?: Array<string> | null;
    excludeWatched?: boolean;
    partnerUsername?: string | null;
}

