/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PrimeTimeStatsDto { 
    peakDay: string | null;
    peakDayCount: number;
    peakMonth: string | null;
    peakMonthCount: number;
    slumpDay: string | null;
    slumpDayCount: number;
    slumpMonth: string | null;
    slumpMonthCount: number;
}

