/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProviderDiagnosticsDto { 
    tmdbStatus: string;
    tmdbLatencyMs: number;
    omdbStatus: string;
    omdbLatencyMs: number;
    backendStatus: string;
    backendLatencyMs: number;
}

