/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecommendedMovieDto { 
    movieId: string;
    title: string;
    directorName: string;
    releaseYear: number;
    matchPercentage: number;
    recommendationReason: string;
    posterUrl?: string | null;
    runtimeMinutes?: number | null;
    customAverageRating?: number | null;
    easterEggTooltip?: string | null;
}
