/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RouletteRequest { 
    scope: number;
    winningThreshold?: number;
    customSourceIds?: Array<string> | null;
    customSourceTitles?: Array<string> | null;
    excludeWatched?: boolean;
}

