/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SlotMachineRequest { 
    scope: number;
    genre?: string | null;
    decade?: number | null;
    popularity?: string | null;
    rating?: string | null;
    country?: string | null;
    customSourceIds?: Array<string> | null;
    customSourceTitles?: Array<string> | null;
    excludeWatched?: boolean;
}

