/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WrappedMovieDto2 } from './wrapped-movie-dto2';


export interface TopBottomMoviesDto { 
    topRated: Array<WrappedMovieDto2>;
    bottomRated?: Array<WrappedMovieDto2>;
}

