/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id: string;
    username: string;
    email: string;
    role: string;
    canManageCatalog: boolean;
    canAddUsers: boolean;
    canDeleteUsers: boolean;
    canPromoteToAdmin: boolean;
}

