/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WatchlistMovieStatsDto { 
    title: string;
    releaseYear: number | null;
    director: string;
    dateAdded: string;
    customAverageRating?: number | null;
    posterUrl?: string | null;
}

