/**
 * Frametric API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenreCountDto } from './genre-count-dto';
import { ActorCountDto } from './actor-count-dto';
import { DecadeCountDto } from './decade-count-dto';
import { MonthlyActivityDto } from './monthly-activity-dto';
import { DirectorCountDto } from './director-count-dto';


export interface WrappedSummaryDto { 
    year: number;
    totalWatchtimeMinutes: number;
    totalWatches: number;
    uniqueMoviesCount: number;
    topGenres: Array<GenreCountDto>;
    topDirectors: Array<DirectorCountDto>;
    topActors: Array<ActorCountDto>;
    decadeBreakdown: Array<DecadeCountDto>;
    monthlyActivity: Array<MonthlyActivityDto>;
}

